plugins:
  - jekyll-seo-tag

title: Bitcoin Cash Address Translator
url: https://cashaddress.github.io/
description: An online tool for Bitcoin Cash users to convert between the old address format and the newer so-called "Cash Address" format.

social:
  links:
    - https://github.com/cashaddress/cashaddress.github.io